# Generated by Django 5.1.1 on 2024-10-09 08:58

import vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehicle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_pictures/', validators=[vehicle.models.validate_image]),
        ),
    ]
